pages = [
    "Home" => "index.md",
    "Getting Started" => "quickstart.md",
    "Examples" => [
        "Fickian diffusion 1D"   => "examples/fickian_diffusion.md",
        "Darcy column"           => "examples/darcy_column.md",
        "Richards 1D"            => "examples/richards_1d.md",
        "Non-isothermal drying"  => "examples/nonisothermal_drying.md",
        "Biot consolidation"     => "examples/biot_consolidation.md",
    ],
    "Validation" => [
        "Terzaghi consolidation" => "validation/terzaghi.md",
        "Mandel's problem"       => "validation/mandel.md",
        "Cryer's sphere"         => "validation/cryer.md",
        "De Leeuw's cylinder"    => "validation/deleeuw.md",
        "Gardner infiltration"   => "validation/gardner_infiltration.md",
        "Transient drainage"     => "validation/gardner_transient.md",
        "BBM — Bil reference cases" => "validation/bbm_bil.md",
        "Richards — Bil reference case" => "validation/bil_richards.md",
        "Poroplasticity — Bil reference case" => "validation/bil_poroplast.md",
        "Homogenisation — mean field vs FE²" => "validation/bil_mechamic.md",
        "Poroelastic coefficients from a microstructure" => "validation/mfh_poroelastic.md",
        "Thick-walled cylinder — homogenised moduli" => "validation/mfh_thick_cylinder.md",
    ],
    "Writing a model" => "demos/writing_a_model.md",
    "Differentiability" => [
        "Parameter identification" => "demos/parameter_identification.md",
        "Differentiating a solve"  => "demos/solver_sensitivity.md",
    ],
    "API" => "api.md",
    "References" => "references.md",
]
